export const ALLOWED_MENU_ITEMS = {
  MENU_ITEM: 'item',
  LINK: 'link',
  DIVIDER: 'divider',
  CHANGE_LOCALE: 'changeLocale',
  CHANGE_THEME: 'changeTheme'
};

export const MENU_ITEM_TYPES = [
  ALLOWED_MENU_ITEMS.DIVIDER,
  ALLOWED_MENU_ITEMS.LINK,
  ALLOWED_MENU_ITEMS.MENU_ITEM,
  ALLOWED_MENU_ITEMS.CHANGE_LOCALE,
  ALLOWED_MENU_ITEMS.CHANGE_THEME
];
